/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class foma_App */

#ifndef _Included_foma_App
#define _Included_foma_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     foma_App
 * Method:    getFST
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_foma_App_getFST
  (JNIEnv *, jobject, jstring);

/*
 * Class:     foma_App
 * Method:    destroyFST
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_foma_App_destroyFST
  (JNIEnv *, jobject, jlong);

/*
 * Class:     foma_App
 * Method:    applyUp
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_foma_App_applyUp
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     foma_App
 * Method:    applyDown
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_foma_App_applyDown
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
